---
id: Pack
name: Pack
full: Data packing library
description: >-
  A replacement library for serialize()/json_encode() that will automatically
  use the most efficient serialization available based on the input.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha1
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/compress_fast: ^2
      horde/exception: ^3
  optional:
    composer:
      horde/test: ^3
    ext:
      igbinary: ^1.2
      msgpack: '*'
      json: '*'
