language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        yes "" | pecl install channel://pecl.php.net/msgpack-beta;
    else
        phpenv config-add .travis.ini;
        yes "" | pecl install channel://pecl.php.net/igbinary channel://pecl.php.net/msgpack-0.5.7;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - yes no | pecl install channel://pecl.php.net/lzf
  - pecl install channel://pear.horde.org/horde_lz4
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(pear config-get php_dir)/Horde/Test/vendor/phpunit/phpunit/phpunit
