sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        yes "" | pecl install channel://pecl.php.net/msgpack-beta;
    else
        phpenv config-add .travis.ini;
        yes "" | pecl install channel://pecl.php.net/igbinary channel://pecl.php.net/msgpack-0.5.7;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - yes no | pecl install channel://pecl.php.net/lzf
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ] || [ "$TRAVIS_PHP_VERSION" == "7.0" ];
    then
      pear channel-discover pear.horde.org;
      echo "include_path = .:$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/pear" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
    fi
  - pecl install channel://pear.horde.org/horde_lz4
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(find test -name AllTests.php)
